/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.IOFile;
import Model.nhanVien;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Trang
 */
public class formNhanVien extends javax.swing.JPanel {
    private String f;
    private List<nhanVien> ds;
    private DefaultTableModel md;
    
    /**
     * Creates new form nhanVien
     */
    public formNhanVien() {
        initComponents();
        f = "NV.txt";
        String[] cols = {"Mã nhân viên", "Họ và tên"," Địa chỉ", "Số điện thoại"," Bậc lương"};
        md = new DefaultTableModel(cols,0);
        bangnv.setModel(md);
        prepare();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hoTen = new javax.swing.JTextField();
        diaChi = new javax.swing.JTextField();
        soDT = new javax.swing.JTextField();
        bacLuong = new javax.swing.JTextField();
        nhap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangnv = new javax.swing.JTable();

        jLabel1.setText("Họ tên: ");

        jLabel2.setText("Địa chỉ:");

        jLabel3.setText("Số điện thoại:");

        jLabel4.setText("Bậc lương:");

        hoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoTenActionPerformed(evt);
            }
        });

        nhap.setText("Nhập");
        nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapActionPerformed(evt);
            }
        });

        bangnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bangnv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nhap)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hoTen)
                        .addComponent(diaChi)
                        .addComponent(soDT)
                        .addComponent(bacLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(soDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(bacLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(nhap))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoTenActionPerformed

    private void nhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapActionPerformed
        // TODO add your handling code here:
        if(hoTen.getText().isBlank()|| diaChi.getText().isBlank()|| soDT.getText().isBlank()
                || bacLuong.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!");
        } else {
            if(!ds.isEmpty() && ds.size()>0){
                nhanVien.setMa(ds.get(ds.size()-1).getMaNV()+1);
            }
            nhanVien nv = new nhanVien();
            nv.setHoTen(hoTen.getText());
            nv.setDiaChi(diaChi.getText());
            nv.setSoDT(soDT.getText());
            nv.setBacLuong(Integer.parseInt(bacLuong.getText()));
            if(ds.isEmpty()){
                ds.add(nv);
                md.addRow(nv.toObject());
                IOFile.writeFile(f, ds);
            } else{
                boolean ok = false;
                for(nhanVien n : ds){
                    if(!ok && nv.giongNhau(n)){
                        ok = true;
                        JOptionPane.showMessageDialog(this, "Trùng thông tin!");
                        break;       
                    }
                }
                if(!ok){
                    ds.add(nv);
                    md.addRow(nv.toObject());
                    IOFile.writeFile(f, ds);
                }
            }
        }
    }//GEN-LAST:event_nhapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bacLuong;
    private javax.swing.JTable bangnv;
    private javax.swing.JTextField diaChi;
    private javax.swing.JTextField hoTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nhap;
    private javax.swing.JTextField soDT;
    // End of variables declaration//GEN-END:variables

    private void prepare() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        ds = IOFile.readFile(f);
        for(nhanVien i : ds){
            md.addRow(i.toObject());
        }
    }

    
}
